name: Continues Integration

on: [push]

jobs:
  verify-plugin-id:
    name: Verify that the plugin id in plugin.xml not changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Verify plugin id in plugin.xml has not changed
        run: ./verify-plugin-id.sh
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        name: Cache Gradle packages
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build & Test
        run: ./gradlew build --scan
      - if: always()
        name: Publish Test Report
        uses: scacap/action-surefire-report@v1
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: build/reports

  compatibility-stable:
    name: Ensure plugin compatibility against IC releases 2019.3 and current latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Download latest stable
        run: |
          sudo curl -L "https://download.jetbrains.com/product?code=IC&latest&distribution=linux" --output latest.tar.gz
          mkdir latest && tar -xvf latest.tar.gz -C latest --strip-components 1
          ls -al latest

      - name: Build the plugin
        run: ./gradlew buildPlugin

      - name: Validate the plugin
        run: ./gradlew runPluginVerifier -PlocalPaths="$(pwd)/latest"

  format:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Check Java Formatting
        run: ./gradlew verGJF --warning-mode all

      - name: Check Kotlin Formatting
        run: ./gradlew ktlintCheck

  security:
    name: Vulnerabilities Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high
